//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DataTab
    {
        [Display(Name ="设备编号")]
        public string rtu_id { get; set; }
        [Display(Name = "时间")]
        public Nullable<System.DateTime> rtu_time { get; set; }

        [Display(Name = "水位")]
        public string water_level { get; set; }
        [Display(Name = "流量")]
        public string water_flow { get; set; }
        [Display(Name = "压力")]
        public string water_pressure { get; set; }
        [Display(Name = "温度")]
        public string water_tem { get; set; }
        [Display(Name = "PH值")]
        public string water_ph { get; set; }
        [Display(Name = "浊度")]
        public string water_turb { get; set; }
    }
}
