//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class instrument
    {
        [Display(Name = "自增id")]
        public int id { get; set; }
        [Display(Name = "设备名称")]
        public string instru_name { get; set; }
        [Display(Name = "设备编号")]
        public string rtu_id { get; set; }
        [Display(Name = "类型编码")]
        public string instru_type { get; set; }
        [Display(Name = "状态")]
        public string instru_state { get; set; }
        [Display(Name = "设备类型")]
        public string other { get; set; }

    }
}
