//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class monitordata
    {
        [Display(Name = "自增Id")]
        public int id { get; set; }
        [Display(Name = "设备名称")]
        public string instru_name { get; set; }
        [Display(Name = "数据值")]
        public string instru_value { get; set; }
        [Display(Name = "时间")]
        public Nullable<System.DateTime> instru_time { get; set; }
        [Display(Name = "其他")]
        public string other { get; set; }
    }
}
