//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class rtu
    {
        public int id { get; set; }
        [Display(Name = "站点编号")]
        public string rtu_id { get; set; }
        [Display(Name = "站点名称")]
        public string rtu_name { get; set; }
        [Display(Name = "站点单位")]
        public string rtu_region { get; set; }
        [Display(Name = "SIM号")]
        public string rtu_sim { get; set; }
        [Display(Name = "安装单位")]
        public string rtu_unit { get; set; }
        [Display(Name = "其他")]
        public string other { get; set; }
    }
}
