//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StationTab
    {
        [Display(Name = "设备编号")]
        public string rtu_id { get; set; }
        [Display(Name = "设备名称")]
        public string rtu_name { get; set; }
        [Display(Name = "安装地点")]
        public string rtu_region { get; set; }
        [Display(Name = "检测点名称")]
        public string sta_name { get; set; }
        [Display(Name = "SIM卡号")]
        public string SIM { get; set; }
        [Display(Name = "传感器类型号")]
        public string rtu_type { get; set; }
        [Display(Name ="安装单位")]
        public string rtu_unit { get; set; }
    }
}
