//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersTab
    {
        public int id { get; set; }
        [Display(Name = "用户名")]
        public string user_name { get; set; }
        [Display(Name = "密码")]
        public string user_password { get; set; }
        [Display(Name = "地区")]
        public string user_region { get; set; }
        [Display(Name = "所属单位")]
        public string user_unit { get; set; }
        [Display(Name = "联系电话")]
        public string user_tel { get; set; }
        [Display(Name = "联系邮箱")]
        public string user_mail { get; set; }
        [Display(Name = "姓名")]
        public string name { get; set; }
        [Display(Name = "角色")]
        public string user_role { get; set; }
    }
}
